# Generated by Django 3.1 on 2020-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_auto_20200903_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'buses'},
        ),
        migrations.AddField(
            model_name='bus',
            name='site_count',
            field=models.IntegerField(default=0),
        ),
    ]
